ServerName localhost
ErrorLog /dev/stderr
CustomLog /dev/stdout combined

<VirtualHost *:80>
    DocumentRoot /app/public
    <Directory /app/public>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>